apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-java-springboot-basic
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/test-rhtap-44-tenant/load-app-bf3bed38-fe3d-45ef-a13d-90d91a8341d1/devfile-sample-java-springboot-basic@sha256:4aa70188f1eebcce6542e92b6947afed0a90c3659f79d15167193c48bd0ac749
        name: my-java-springboot
        resources: {}
status: {}
